### ISSUE TITLE
So... what?

### ISSUE THREAD

**Issue by jiri-psenicka** [samkaufman/tes3mp-mac-pkg#1]
After running the app, it only shows "Server Browser" window without any further options whatsoever or any help or documentation on how to run this thing.

**Comment by samkaufman** [comment]
@jiri-psenicka You can join a server by selecting one of the servers in that browser window. If you'd like to run your own server, you'll want to run `/Applications/TES3MP.app/Contents/MacOS/tes3mp-server` in a terminal.

Beyond that, you're looking for *general* TES3MP support, not support with this Mac build. Check out the Getting Started section on https://tes3mp.com.

Closing this because it is not an issue with the Mac build.

**Comment by jiri-psenicka** [comment]
My bad, I didn't mention I don't see any servers and can not refresh. No error message. I got openMW configured and runs well.

**Comment by backlabs1** [comment]
I opened <https://github.com/TES3MP/TES3MP/issues/686> for the actual underlying problem.
